- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: custom-api
          title: Proxmox-VE Stats
          cache: 1m
          url: https://${PROXMOXVE_URL}/api2/json/cluster/resources
          allow-insecure: true
          headers:
            Accept: application/json
            Authorization: PVEAPIToken=${PROXMOXVE_KEY}
          template: |
            <div class="flex flex-column gap-5">
              <div class="flex justify-between text-center">
                <div>
                  {{ $nodes_online := len (.JSON.Array "data.#(type==\"node\")#|#(status==\"online\")#") }}
                  {{ $nodes_total := len (.JSON.Array "data.#(type==\"node\")#") }}
                  <div class="color-highlight size-h3">{{ $nodes_online }}/{{ $nodes_total }}</div>
                  <div class="size-h5 uppercase">Node</div>
                </div>
                <div>
                  {{ $lxc_running := len (.JSON.Array "data.#(type==\"lxc\")#|#(status==\"running\")#|#(template==0)#") }}
                  {{ $lxc_total := len (.JSON.Array "data.#(type==\"lxc\")#|#(template==0)#") }}
                  <div class="color-highlight size-h3">{{ $lxc_running }}/{{ $lxc_total }}</div>
                  <div class="size-h5 uppercase">LXC</div>
                </div>
                <div>
                  {{ $qemu_running := len (.JSON.Array "data.#(type==\"qemu\")#|#(status==\"running\")#|#(template==0)#") }}
                  {{ $qemu_total := len (.JSON.Array "data.#(type==\"qemu\")#|#(template==0)#") }}
                  <div class="color-highlight size-h3">{{ $qemu_running }}/{{ $qemu_total }}</div>
                  <div class="size-h5 uppercase">VM</div>
                </div>
                <div>
                    {{ $storage_available := len (.JSON.Array "data.#(type==\"storage\")#|#(status==\"available\")#") }}
                    {{ $storage_total := len (.JSON.Array "data.#(type==\"storage\")#") }}
                    <div class="color-highlight size-h3">{{ $storage_available }}/{{ $storage_total }}</div>
                    <div class="size-h5 uppercase">Storage</div>
                </div>
              </div>
            </div>
        
        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://codewithmukesh.com/rss.xml
              title: codewithmukesh

    - size: full
      widgets:
        - type: search
          autofocus: true

        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Proxmox
              url: https://proxmox.jarvs.dev/
              check-url: https://192.168.1.10:8006
              icon: si:proxmox
              allow-insecure: true
            - title: Plex
              url: https://plex.jarvs.dev/
              icon: si:plex
              check-url: http://192.168.1.100:32400
            - title: SpeedTest
              url: https://speed.jarvs.dev/
              icon: si:speedtest
              check-url: http://192.168.1.205:8070
            - title: qBittorrent
              url: https://torrent.venomserver.dev/
              icon: si:qbittorrent
              check-url: http://192.168.1.101

        - type: videos
          channels:
            - UCBgmocEUwo8s_IKOHjIecPw #codewithmukesh

        - type: group
          widgets:
            - type: reddit
              subreddit: dotnet
              show-thumbnails: true
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Varkala
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: custom-api
          cache: 1h
          title: Internet Speed
          title-url: ${SPEEDTEST_URL}
          url: ${SPEEDTEST_URL}/api/v1/results/latest
          headers:
            Authorization: Bearer ${SPEEDTEST_TRACKER_API_TOKEN}
            Accept: application/json
          subrequests:
            stats:
              url: ${SPEEDTEST_URL}/api/v1/stats
              headers:
                Authorization: Bearer ${SPEEDTEST_TRACKER_API_TOKEN}
                Accept: application/json
          options:
            showPercentageDiff: true
          template: |
            {{ $showPercentage := .Options.BoolOr "showPercentageDiff" true }}

            {{ $stats := .Subrequest "stats" }}
            <div class="flex justify-between text-center margin-block-3">
            <div>
                {{ $downloadChange := percentChange ($stats.JSON.Float "data.download.avg_bits") (.JSON.Float "data.download_bits")
                }}
                {{ if $showPercentage }}
                <div
                class="size-small {{ if gt $downloadChange 0.0 }}color-positive{{ else if lt $downloadChange 0.0 }}color-negative{{ else }}color-primary{{ end }}"
                style="display: inline-flex; align-items: center;">
                {{ $downloadChange | printf "%+.1f%%" }}
                {{ if gt $downloadChange 0.0 }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    style="height: 1em; margin-left: 0.25em;" class="size-4">
                    <path fill-rule="evenodd"
                    d="M9.808 4.057a.75.75 0 0 1 .92-.527l3.116.849a.75.75 0 0 1 .528.915l-.823 3.121a.75.75 0 0 1-1.45-.382l.337-1.281a23.484 23.484 0 0 0-3.609 3.056.75.75 0 0 1-1.07.01L6 8.06l-3.72 3.72a.75.75 0 1 1-1.06-1.061l4.25-4.25a.75.75 0 0 1 1.06 0l1.756 1.755a25.015 25.015 0 0 1 3.508-2.85l-1.46-.398a.75.75 0 0 1-.526-.92Z"
                    clip-rule="evenodd" />
                </svg>
                {{ else if lt $downloadChange 0.0 }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    style="height: 1em; margin-left: 0.25em;" class="size-4">
                    <path fill-rule="evenodd"
                    d="M1.22 4.22a.75.75 0 0 1 1.06 0L6 7.94l2.761-2.762a.75.75 0 0 1 1.158.12 24.9 24.9 0 0 1 2.718 5.556l.729-1.261a.75.75 0 0 1 1.299.75l-1.591 2.755a.75.75 0 0 1-1.025.275l-2.756-1.591a.75.75 0 1 1 .75-1.3l1.097.634a23.417 23.417 0 0 0-1.984-4.211L6.53 9.53a.75.75 0 0 1-1.06 0L1.22 5.28a.75.75 0 0 1 0-1.06Z"
                    clip-rule="evenodd" />
                </svg>
                {{ end }}
                </div>
                {{ end }}
                <div class="color-highlight size-h3">{{ .JSON.Float "data.download_bits" | mul 0.000001 | printf "%.1f" }}</div>
                <div class="size-h6">DOWNLOAD</div>
            </div>
            <div>
                {{ $uploadChange := percentChange ($stats.JSON.Float "data.upload.avg_bits") (.JSON.Float "data.upload_bits") }}
                {{ if $showPercentage }}
                <div
                class="size-small {{ if gt $uploadChange 0.0 }}color-positive{{ else if lt $uploadChange 0.0 }}color-negative{{ else }}color-primary{{ end }}"
                style="display: inline-flex; align-items: center;">
                {{ $uploadChange | printf "%+.1f%%" }}
                {{ if gt $uploadChange 0.0 }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    style="height: 1em; margin-left: 0.25em;" class="size-4">
                    <path fill-rule="evenodd"
                    d="M9.808 4.057a.75.75 0 0 1 .92-.527l3.116.849a.75.75 0 0 1 .528.915l-.823 3.121a.75.75 0 0 1-1.45-.382l.337-1.281a23.484 23.484 0 0 0-3.609 3.056.75.75 0 0 1-1.07.01L6 8.06l-3.72 3.72a.75.75 0 1 1-1.06-1.061l4.25-4.25a.75.75 0 0 1 1.06 0l1.756 1.755a25.015 25.015 0 0 1 3.508-2.85l-1.46-.398a.75.75 0 0 1-.526-.92Z"
                    clip-rule="evenodd" />
                </svg>
                {{ else if lt $uploadChange 0.0 }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    style="height: 1em; margin-left: 0.25em;" class="size-4">
                    <path fill-rule="evenodd"
                    d="M1.22 4.22a.75.75 0 0 1 1.06 0L6 7.94l2.761-2.762a.75.75 0 0 1 1.158.12 24.9 24.9 0 0 1 2.718 5.556l.729-1.261a.75.75 0 0 1 1.299.75l-1.591 2.755a.75.75 0 0 1-1.025.275l-2.756-1.591a.75.75 0 1 1 .75-1.3l1.097.634a23.417 23.417 0 0 0-1.984-4.211L6.53 9.53a.75.75 0 0 1-1.06 0L1.22 5.28a.75.75 0 0 1 0-1.06Z"
                    clip-rule="evenodd" />
                </svg>
                {{ end }}
                </div>
                {{ end }}
                <div class="color-highlight size-h3">{{ .JSON.Float "data.upload_bits" | mul 0.000001 | printf "%.1f" }}</div>
                <div class="size-h6">UPLOAD</div>
            </div>
            <div>
                {{ $pingChange := percentChange ($stats.JSON.Float "data.ping.avg") (.JSON.Float "data.ping") }}
                {{ if $showPercentage }}
                <div
                class="size-small {{ if gt $pingChange 0.0 }}color-negative{{ else if lt $pingChange 0.0 }}color-positive{{ else }}color-primary{{ end }}"
                style="display: inline-flex; align-items: center;">
                {{ $pingChange | printf "%+.1f%%" }}
                {{ if lt $pingChange 0.0 }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    style="height: 1em; margin-left: 0.25em;" class="size-4">
                    <path fill-rule="evenodd"
                    d="M1.22 4.22a.75.75 0 0 1 1.06 0L6 7.94l2.761-2.762a.75.75 0 0 1 1.158.12 24.9 24.9 0 0 1 2.718 5.556l.729-1.261a.75.75 0 0 1 1.299.75l-1.591 2.755a.75.75 0 0 1-1.025.275l-2.756-1.591a.75.75 0 1 1 .75-1.3l1.097.634a23.417 23.417 0 0 0-1.984-4.211L6.53 9.53a.75.75 0 0 1-1.06 0L1.22 5.28a.75.75 0 0 1 0-1.06Z"
                    clip-rule="evenodd" />
                </svg>
                {{ else if gt $pingChange 0.0 }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    style="height: 1em; margin-left: 0.25em;" class="size-4">
                    <path fill-rule="evenodd"
                    d="M9.808 4.057a.75.75 0 0 1 .92-.527l3.116.849a.75.75 0 0 1 .528.915l-.823 3.121a.75.75 0 0 1-1.45-.382l.337-1.281a23.484 23.484 0 0 0-3.609 3.056.75.75 0 0 1-1.07.01L6 8.06l-3.72 3.72a.75.75 0 1 1-1.06-1.061l4.25-4.25a.75.75 0 0 1 1.06 0l1.756 1.755a25.015 25.015 0 0 1 3.508-2.85l-1.46-.398a.75.75 0 0 1-.526-.92Z"
                    clip-rule="evenodd" />
                </svg>
                {{ end }}
                </div>
                {{ end }}
                <div class="color-highlight size-h3">{{ .JSON.Float "data.ping" | printf "%.0f ms" }}</div>
                <div class="size-h6">PING</div>
            </div>
            </div>

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - fullstackhero/dotnet-starter-kit
        
        - type: bookmarks
          groups:
            - title: General
              links:
                - title: Gmail
                  url: https://mail.google.com/mail/u/0/
                - title: Amazon
                  url: https://www.amazon.com/
                - title: Github
                  url: https://github.com/
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Prime Video
                  url: https://www.primevideo.com/
                - title: Disney+
                  url: https://www.disneyplus.com/
            - title: Social
              links:
                - title: Reddit
                  url: https://www.reddit.com/
                - title: Twitter
                  url: https://twitter.com/
                - title: Instagram
                  url: https://www.instagram.com/