services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000               # Set to the user ID on your host
      - PGID=1000               # Set to the group ID on your host
      - TZ=Asia/Kolkata         # Your timezone
      - WEBUI_PORT=8080         # Web UI port
    volumes:
      - ./config:/config
      - /mnt/media:/downloads
    ports:
      - 8080:8080               # Web UI
      - 6881:6881               # Torrent port
      - 6881:6881/udp           # Torrent port (UDP)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - media-network
      
networks:
  media-network:
    external: true