services:
  alpine:
    container_name: alpine
    image: alpine
    command: sleep infinity
    networks:
      - media-network
networks:
  media-network:
    name: media-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.39.0.0/24
