services:
  glance:
      container_name: glance
      image: glanceapp/glance
      restart: unless-stopped
      volumes:
        - ./glance/config:/app/config
        - ./glance/assets:/app/assets
      ports:
        - 8080:8080
      env_file: .env