services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host  # Best for Plex performance and DLNA
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK=022
      - TZ=Asia/Kolkata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.jarvs.dev`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=cloudflare"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    volumes:
      - ./config:/config
      - /mnt/media:/media
