services:
  glance:
      container_name: glance
      image: glanceapp/glance
      restart: unless-stopped
      volumes:
        - ./config:/app/config
        - ./assets:/app/assets
      ports:
        - 8080:8080
      env_file: .env
      networks:
        - core-network

networks:
  core-network:
    external: true