services:
  glance:
      container_name: glance
      image: glanceapp/glance
      restart: unless-stopped
      volumes:
        - ./config:/app/config/
        - ./assets:/app/assets/
      env_file: .env  
      ports:
        - 8080:8080
      networks:
        - core-network

networks:
  core-network:
    external: true
