services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    networks:
      - core-network
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080" # dashboard port (optional external access)
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      # Required for Traefik to detect other containers and their labels
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Static and dynamic Traefik configuration files
      - ./traefik.yaml:/traefik.yaml:ro
      - ./config.yaml:/config.yaml:ro
      - ./config/externals.yml:/etc/traefik/dynamic/externals.yml:ro
      
      # ACME cert storage
      - ./acme.json:/acme.json

      # Logs
      - ./logs:/var/log/traefik
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"

      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.jarvs.dev`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      # HTTPS router for dashboard
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.jarvs.dev`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=jarvs.dev"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.jarvs.dev"

      # Directly expose dashboard without auth (not recommended for public internet)
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  core-network:
    external: true
